version: "3"
services:
    nginx:
        image: nginx:1.20
        container_name: Nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8017:80"
            - "8020:8020"
            - "443:443"
        volumes:
            - ./:/app
            - ./docker-conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        container_name: PHP
        build:
            context: ./docker-conf/php
        volumes:
            - ./:/app
            - ./docker-conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
            - ./docker-conf/php/php.ini:/usr/local/etc/php/php.ini:rw
            - ./docker-conf/php/openssl.cnf:/etc/ssl/openssl.cnf:rw
#        env_file:
#            - "./.env"
#        user: 1000:0
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"
        extra_hosts:
            - "docker.for.mac.host.internal:172.17.0.1"
        working_dir: /app
